# Generated by Django 3.0.6 on 2020-06-01 10:55

from django.db import migrations, models
from django.core.management import call_command


def populate_db(apps, schema_editor):
    call_command('loaddata', 'dog_data.json', verbosity=2)


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
